# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=64, verbose_name=b'state')),
                ('city', models.CharField(max_length=64, verbose_name=b'city')),
                ('username', models.CharField(max_length=64, verbose_name=b'user')),
                ('message', models.TextField(verbose_name=b'message')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'date')),
            ],
            options={
                'ordering': ['state', 'city', 'create_time'],
            },
        ),
        migrations.CreateModel(
            name='MessageStatsURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['updated'],
            },
        ),
    ]
