# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=64, verbose_name=b'State')),
                ('city', models.CharField(max_length=64, verbose_name=b'City')),
                ('username', models.CharField(max_length=64, verbose_name=b'User')),
                ('message', models.TextField(verbose_name=b'Message')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'Date')),
            ],
            options={
                'ordering': ['state', 'city', 'create_time'],
            },
        ),
    ]
